// <auto-generated />
using System;
using CalorieTrackerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieTrackerAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalorieTrackerAPI.Models.ActivityLevel", b =>
                {
                    b.Property<int>("ActivityLevelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLevelID"));

                    b.Property<double>("Multiplier")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ActivityLevelID");

                    b.ToTable("ActivityLevels");

                    b.HasData(
                        new
                        {
                            ActivityLevelID = 1,
                            Multiplier = 1.2,
                            Name = "Sedentary"
                        },
                        new
                        {
                            ActivityLevelID = 2,
                            Multiplier = 1.375,
                            Name = "Lightly active"
                        },
                        new
                        {
                            ActivityLevelID = 3,
                            Multiplier = 1.55,
                            Name = "Moderately active"
                        },
                        new
                        {
                            ActivityLevelID = 4,
                            Multiplier = 1.7250000000000001,
                            Name = "Highly active"
                        },
                        new
                        {
                            ActivityLevelID = 5,
                            Multiplier = 1.8999999999999999,
                            Name = "Extremely active"
                        });
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.FoodItem", b =>
                {
                    b.Property<int>("FoodItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodItemID"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.HasKey("FoodItemID");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.Goal", b =>
                {
                    b.Property<int>("GoalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoalID"));

                    b.Property<int>("CalorieAdjustment")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GoalID");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            GoalID = 1,
                            CalorieAdjustment = -500,
                            Name = "Weightloss"
                        },
                        new
                        {
                            GoalID = 2,
                            CalorieAdjustment = 0,
                            Name = "Maintain"
                        },
                        new
                        {
                            GoalID = 3,
                            CalorieAdjustment = 300,
                            Name = "Musclebuilding"
                        });
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.Meal", b =>
                {
                    b.Property<int>("MealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("SelectedMealType")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MealID");

                    b.HasIndex("UserID");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.MealEntry", b =>
                {
                    b.Property<int>("MealEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealEntryID"));

                    b.Property<int>("FoodItemID")
                        .HasColumnType("int");

                    b.Property<int>("MealID")
                        .HasColumnType("int");

                    b.Property<double>("QuantityInGrams")
                        .HasColumnType("float");

                    b.HasKey("MealEntryID");

                    b.HasIndex("FoodItemID");

                    b.HasIndex("MealID");

                    b.ToTable("MealEntries");
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int>("ActivityLevelID")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GoalID")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SelectedGender")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("UserID");

                    b.HasIndex("ActivityLevelID");

                    b.HasIndex("GoalID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.WaterLog", b =>
                {
                    b.Property<int>("WaterLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WaterLogID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MlIngested")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("WaterLogID");

                    b.HasIndex("UserID");

                    b.ToTable("WaterLogs");
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.Meal", b =>
                {
                    b.HasOne("CalorieTrackerAPI.Models.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.MealEntry", b =>
                {
                    b.HasOne("CalorieTrackerAPI.Models.FoodItem", "FoodItem")
                        .WithMany("MealEntries")
                        .HasForeignKey("FoodItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTrackerAPI.Models.Meal", "Meal")
                        .WithMany("MealEntries")
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.User", b =>
                {
                    b.HasOne("CalorieTrackerAPI.Models.ActivityLevel", "ActivityLevel")
                        .WithMany("Users")
                        .HasForeignKey("ActivityLevelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTrackerAPI.Models.Goal", "Goal")
                        .WithMany("Users")
                        .HasForeignKey("GoalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityLevel");

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.WaterLog", b =>
                {
                    b.HasOne("CalorieTrackerAPI.Models.User", "User")
                        .WithMany("WaterLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.ActivityLevel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.FoodItem", b =>
                {
                    b.Navigation("MealEntries");
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.Goal", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.Meal", b =>
                {
                    b.Navigation("MealEntries");
                });

            modelBuilder.Entity("CalorieTrackerAPI.Models.User", b =>
                {
                    b.Navigation("Meals");

                    b.Navigation("WaterLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
